//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public decimal CallID { get; set; }
        public Nullable<System.DateTime> CallDataTine { get; set; }
        public string CallDestinationAddress { get; set; }
        public string CallOriginatingAddress { get; set; }
        public string CallInboundOutBound { get; set; }
        public Nullable<decimal> CallRingingDuration { get; set; }
        public Nullable<decimal> CallAcceptedDuration { get; set; }
        public string CallAgent { get; set; }
        public string CallQueue { get; set; }
        public Nullable<decimal> CallTalkTime { get; set; }
        public Nullable<decimal> CallWaitTime { get; set; }
        public Nullable<int> ImportSessionID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ResourceID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ImportSession ImportSession { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
